# Generated by Django 5.1.2 on 2024-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=300, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufactured', models.CharField(blank=True, max_length=100, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Products')),
            ],
        ),
    ]
