# Generated by Django 5.1.2 on 2024-11-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_cartdb_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Prod_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_Images'),
        ),
    ]
